# Data-diff Configuration File
# Using reusable database connections

# =============================================================================
# REUSABLE DATABASE CONNECTIONS
# =============================================================================

[database.mysql_test]
driver = "mysql"
host = "mysql-datadiff"
port = 3306
user = "test"
password = "test"
database = "testdb"

[database.oracle_test]
driver = "oracle"
host = "oracle-datadiff"
port = 1521
user = "system"
password = "oracle"
database = "XE"

# =============================================================================
# GLOBAL DEFAULTS
# =============================================================================

[run.default]
stats = false

# =============================================================================
# COMPARISON RUNS (using reusable database references)  
# =============================================================================

# Products comparison (identical data)
[run.products_basic]
key_columns = ["id", "ID"]

[run.products_basic.1]
database = "mysql_test"
table = "products"

[run.products_basic.2]
database = "oracle_test"
table = "PRODUCTS"

# Customers comparison (identical data)
[run.customers_basic]
key_columns = ["id", "ID"]

[run.customers_basic.1]
database = "mysql_test"
table = "customers"

[run.customers_basic.2]
database = "oracle_test"
table = "CUSTOMERS"

# Orders comparison (identical data)
[run.orders_basic]
key_columns = ["id", "ID"]

[run.orders_basic.1]
database = "mysql_test"
table = "orders"

[run.orders_basic.2]
database = "oracle_test"
table = "ORDERS"

# Products comparison with detailed stats
[run.products_stats]
key_columns = ["id", "ID"]
stats = true

[run.products_stats.1]
database = "mysql_test"
table = "products"

[run.products_stats.2]
database = "oracle_test"
table = "PRODUCTS"

# Products comparison with limit
[run.products_limited]
key_columns = ["id", "ID"]
limit = 3

[run.products_limited.1]
database = "mysql_test"
table = "products"

[run.products_limited.2]
database = "oracle_test"
table = "PRODUCTS"

# All tables comparison (comprehensive test)
[run.all_tables_summary]
key_columns = ["id", "ID"]
stats = true

[run.all_tables_summary.1]
database = "mysql_test"
table = "products"

[run.all_tables_summary.2]
database = "oracle_test"
table = "PRODUCTS"

# =============================================================================
# COMPARISON RUNS (with column selection)  
# =============================================================================

# Comparison with different field counts - Employee table
# MySQL has 10 fields, Oracle has 6 fields - compare only common fields
[run.employees_common_fields.1]
database = "mysql_test"
table = "employees"

[run.employees_common_fields.2]
database = "oracle_test"
table = "EMPLOYEES"

[run.employees_common_fields]
key_columns = ["id", "ID"]
columns = ["id", "first_name", "last_name", "email", "department", "salary"]
stats = true

# Product Categories with different field counts
# MySQL has 10 fields, Oracle has 4 fields - compare only common fields
[run.categories_common_fields.1]
database = "mysql_test"
table = "product_categories"

[run.categories_common_fields.2]
database = "oracle_test"
table = "PRODUCT_CATEGORIES"

[run.categories_common_fields]
key_columns = ["category_id", "CATEGORY_ID"]
columns = ["category_id", "category_name", "parent_category_id", "is_active"]
stats = true

# Employees comparison - showing salary differences only
[run.employees_salary_diff.1]
database = "mysql_test"
table = "employees"

[run.employees_salary_diff.2]
database = "oracle_test"
table = "EMPLOYEES"

[run.employees_salary_diff]
key_columns = ["id", "ID"]
columns = ["id", "first_name", "last_name", "salary"]
limit = 10


